#Expyriment 1.0.0 (Python 3.12.2), .xpe-file, coding: UTF-8
#date: Sat Sep 20 2025 14:09:56
#sha1: 75732f
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Darwin', node='Riyas-MacBook-Air.local', release='25.0.0', version='Darwin Kernel Version 25.0.0: Mon Aug 25 21:12:01 PDT 2025; root:xnu-12377.1.9~3/RELEASE_ARM64_T8132', machine='x86_64')
Time,Type,Event,Value,Detail,Detail2
1975,design,log,
#design: #exp: test
#design: block_cnt,block_id,trial_cnt,trial_id
1975,design,logged,
1975,Experiment,started
1992,Stimulus,presented,0
1992,stderr,received,'Traceback (most recent call last):'
1992,stderr,received,'  File "/Users/riyajain/Desktop/Fall 2025/CORE-1/expyriment/# test fucking testing testing.py", line 13, in <module>'
1992,stderr,received,'    while s.absolute_position < (100,0):'
1992,stderr,received,'          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'
1992,stderr,received,"TypeError: '<' not supported between instances of 'list' and 'tuple'"
